import type { Metadata } from "next"
import { DM_Sans } from "next/font/google"
import "./globals.css"
import clsx from "clsx"

const dm_Sans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Sage Dev Craft Dark",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={clsx(dm_Sans.className, `antialiased`)}>{children}</body>
    </html>
  )
}
